version: 2.1
executors:
  alpine:
    docker:
      - image: fr3akyphantom/phoenix_firmware_dumper:latest
        auth:
          username: fr3akyphantom
          password: "$DOCKERHUB_TOKEN"
    working_directory: /home
jobs:
  build:
    executor: alpine
    steps:
      - run:
          name: Clone the Dumper
          command: |
            git config --global user.email "$GitHubMail"
            git config --global user.name "$GitHubName"
            git clone https://github.com/DroidDumps/phoenix_firmware_dumper /home/phoenix_dumper
      - run:
          name: Set Vars
          command: |
            cd /home/phoenix_dumper
            echo "$GITHUB_TOKEN" > .github_token
            echo "$GIT_ORG" > .github_orgname
            echo "$TG_TOKEN" > .tg_token
            echo "$CHAT_ID" > .tg_chat
workflows:
  workstation:
    jobs:
      - build:
          context: phoenix-context
